import { getSupabaseServerClient } from "@/lib/supabase/server";
import { askNexus } from "./ask";
import { spendDailyBudget } from "./limits";

/**
 * The daily market brief: one AI-written summary per UTC day, generated by
 * the poller (app/api/internal/poll/route.ts, group "brief"), stored in
 * Supabase, and shown on the home page. It's written with the same grounded
 * tools as Ask Nexus, so every number in it comes from live data fetched at
 * generation time. One Gemini call per day, regardless of traffic.
 */

export type Brief = { day: string; body: string; model: string | null };

const BRIEF_PROMPT =
  "Write today's NEXUS market brief for the home page, as three short paragraphs separated by blank lines: " +
  "(1) overall market mood, using the market overview and the Fear & Greed reading; " +
  "(2) the biggest gainers and losers among the top coins; " +
  "(3) what Polymarket's crowd expects for Bitcoin at the next settlement, if that data is available (otherwise skip this paragraph). " +
  "About 110 words in total. Use only tool data. No headings, no bullet points, no advice.";

/** Don't write "today's" brief in the first hours of the UTC day, when there
 * is barely any of the day's movement to describe. */
const EARLIEST_UTC_HOUR = 7;

export async function getLatestBrief(): Promise<Brief | null> {
  if (!process.env.SUPABASE_URL || !process.env.SUPABASE_SERVICE_ROLE_KEY) return null;
  try {
    const { data } = await getSupabaseServerClient()
      .from("ai_briefs")
      .select("day, body, model")
      .order("day", { ascending: false })
      .limit(1)
      .maybeSingle();
    return data ? { day: data.day as string, body: data.body as string, model: (data.model as string) ?? null } : null;
  } catch (err) {
    console.warn("[brief] read failed", err);
    return null;
  }
}

export type EnsureResult = { status: "exists" | "generated" | "too-early" | "unavailable"; detail?: string };

export async function ensureTodaysBrief(now = new Date()): Promise<EnsureResult> {
  if (!process.env.SUPABASE_URL || !process.env.SUPABASE_SERVICE_ROLE_KEY) return { status: "unavailable", detail: "no database" };
  if (!process.env.GEMINI_API_KEY) return { status: "unavailable", detail: "no Gemini key" };

  const day = now.toISOString().slice(0, 10);
  const supabase = getSupabaseServerClient();

  const { data: existing } = await supabase.from("ai_briefs").select("day").eq("day", day).maybeSingle();
  if (existing) return { status: "exists" };
  if (now.getUTCHours() < EARLIEST_UTC_HOUR) return { status: "too-early" };
  if (!(await spendDailyBudget())) return { status: "unavailable", detail: "daily AI budget used" };

  try {
    const { answer, model } = await askNexus([], BRIEF_PROMPT);
    const body = answer.trim();
    // A brief that's tiny or enormous means the model misfired — better no
    // brief than a bad one; the next poll will retry.
    if (body.length < 200 || body.length > 1400) return { status: "unavailable", detail: `unusable length ${body.length}` };
    const { error } = await supabase.from("ai_briefs").upsert({ day, body, model });
    if (error) return { status: "unavailable", detail: error.message };
    return { status: "generated" };
  } catch (err) {
    return { status: "unavailable", detail: err instanceof Error ? err.message : String(err) };
  }
}
